Steps:
- name: 'gcr.io/cloud-builders/docker'
  env: ['PROJECT_ROOT=$REPO_NAME']
  
- name: 'us.gcr.io/tangerine-dev-171912/appengine:latest'
  args: ['cd', 'getting-started-java/bookshelf/2-structured-data']
  env: ['PROJECT_ROOT=$REPO_NAME']
  
- name: 'us.gcr.io/tangerine-dev-171912/appengine'
  args: ['mvn', 'appengine:deploy', '-DprojectID=tangerine-dev-171912']
  
images:
 - 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID'
