- name: 'gcr.io/cloud-builders/mvn'
  env: ['PROJECT_ROOT=$REPO_NAME']
  
- name: '$REPO_NAME'
  args: ['cd', 'getting-started-java/bookshelf/2-structured-data']
    
- name: 'us.gcr.io/tangerine-dev-171912/appengine'
  args: ['mvn', 'appengine:deploy', '-DprojectID=tangerine-dev-171912']
